@startuml

package domotique {

class Telecommande {

    + Telecommande()
    + ajouterLampe(nouvelleLampe : Lampe)
    + ajouterHifi(nouvelleHifi : Hifi)
    + activerLampe(indiceLampe : int)
    + activerHifi(indiceHifi : int)
    + desactiverLampe(indiceLampe : int)
    + desactiverHifi(indiceHifi : int)
    + activerTout()
    + getLampe(indiceLampe : int) : Lampe
    + getHifi(indiceHifi : int) : Hifi
    + toString() : String
}

class Lampe {
    - nom : String
    - allume : boolean

    + Lampe(paramNom : String)
    + allumer()
    + eteindre()
    + isAllume() : boolean
    + toString() : String
}

class Hifi {
    - son : int

    + allumer()
    + eteindre()
    + toString() : String
}

}

' Relations
Telecommande " 1 " <--- " * " Lampe : -lampes
Telecommande " 1 " <--- " * " Hifi : -hifis

@enduml